[build]
  command = "npm run build"
  publish = ".next"
  functions = "api"

[build.environment]
  NODE_VERSION = "18"
  # Environment variables must be set in Netlify dashboard
  # Required: GEMINI_API_KEY
  # Optional: ELEVENLABS_API_KEY, ELEVENLABS_VOICE_ID, ELEVENLABS_MODEL_ID

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/[...route]"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
